language: python
if: tag IS present
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
os:
  - linux
  - osx
  - windows
dist: bionic
before_install:
  - |-
    case $TRAVIS_OS_NAME in
      windows)
        choco install rust;;
      *)
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh;;
    esac
install:
  - pip3 install -U pip3
  - pip3 install setuptools setuptools-rust wheel
script: python3 -m build || python -m build
deploy:
  on:
    branch: trunk
  provider: pypi
  username: "__token__"
  server: testpipy
  password: 
    secure: VOw5xvUVmeRkY0Y0Az3kMM2QOoNSXo3c7RqM7ePb7jxm7yzRrJJTBhZxjse9mVmPbKkmvlPizVD6GIDe3jYYKNq9MslHlYihMavsBBwFprUerEfsGtRn3KtSwb2pKl1tdVdYtn01Sjv8MljBqclZL+59GSZZAI+TRyQ2Tzh1h/fut0PCNq7zlB7Fv0bT5FWJkGPjGFsnl5rsuAFQupMSMTKaAVhWOTQQXqAXUlV9ZgvjDdAHW6Lu7Rf0u/h93QeG2uHs/sMvtCNRBegD+bGzSW5bNvKuBraBzqrt6y9Nplzr2XilttPMqGJySTmSsbDu5V591zNnVfWH1QZpO+HPVSr3xr7mJxs8G0Sp9/JRUY15PwUULVDn9v+ObRGwJInI1m1pfzSMMMQhjKVt8/ZQ2AHrSS/6vz/z7sO0USppxQ1VlOFIfuVnzeREkdYJwO9j03ZbGAWJGSZIGI18IKBtFmOV6vEuZv48MpKtcwy/x3uMr77tLhRKPJwiFiufi8zQr7qixrNc1ZhfQgBGrusqNBjZ7jtf0RbxE5H0JH9ShO0nYVeSJTrdb2PXzekQCo3J3tnKSaNPfqHIg8qirYenBBjN5oHwqOE8Hh/6Hb7OQZBh1hxj+OGSAGHidOjAKdR2NZ7drZ4ro+hKY3/AlAcADUMamBBNS4cQheUTaOxOV1c=
