language: rust
cache: cargo
os: linux
dist: bionic 

jobs:
  include:
    - services: docker
      env: CIBW_BUILD="cp3*-manylinux*"
    - os: osx
      osx_image: xcode11
      env: CIBW_BUILD="cp3*-macosx*"
    - os: windows
      env:
        - CIBW_BUILD="cp3*-win_amd64"
        - RUSTFLAGS="-Ctarget-feature=+crt-static"
        - CIBW_BEFORE_BUILD="python -m pip install --upgrade pip"
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
      before_install:
        - choco install python --version 3.8.0

env:
  global:
    - CIBW_BEFORE_ALL_LINUX="curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain stable -y"
    - CIBW_BUILD_VERBOSITY="1"   # Make some more noise so that travis doesn't stall
    - CIBW_ENVIRONMENT='PATH="$PATH:$HOME/.cargo/bin"'

before_install:
    - |
      if [ "$TRAVIS_OS_NAME" = "linux" ]; then
          sudo apt-get -y install python3-pip
      fi

install:
    - |
      pip3 install --upgrade pip wheel setuptools setuptools-rust
      pip3 install --upgrade cibuildwheel
      pip3 install --upgrade twine

script: 
  - |
    case $TRAVIS_OS_NAME in
    windows)
      python -m cibuildwheel --output-dir wheelhouse;;
    *)
      python3 -m cibuildwheel --output-dir wheelhouse;;
    esac
  - twine upload --skip-existing wheelhouse/*


